<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    private array $kabupatenData = [
        ['1006', 'KABUPATEN TANJUNG JABUNG TIMUR'],  ['1005', 'KABUPATEN MUARO JAMBI'],
        ['1004', 'KABUPATEN BATANG HARI'],             ['1003', 'KABUPATEN SAROLANGUN'],
        ['1002', 'KABUPATEN MERANGIN'],                ['1001', 'KABUPATEN KERINCI'],
        ['0953', 'DUMAI'],                             ['0951', 'PEKANBARU'],
        ['0909', 'KABUPATEN ROKAN HILIR'],             ['0908', 'KABUPATEN BENGKALIS'],
        ['0907', 'KABUPATEN ROKAN HULU'],              ['0906', 'KABUPATEN KAMPAR'],
        ['0905', 'KABUPATEN SIAK'],                    ['0904', 'KABUPATEN PELALAWAN'],
        ['0903', 'KABUPATEN INDRAGIRI HILIR'],         ['0902', 'KABUPATEN INDRAGIRI HULU'],
        ['0901', 'KABUPATEN KUANTAN SINGINGI'],        ['0857', 'PARIAMAN'],
        ['0856', 'PAYAKUMBUH'],                        ['0855', 'BUKITTINGGI'],
        ['0854', 'PADANG PANJANG'],                    ['0853', 'SAWAH LUNTO'],
        ['0852', 'SOLOK'],                             ['0851', 'PADANG'],
        ['0813', 'KABUPATEN PAYAKUMBUH'],              ['0812', 'KABUPATEN PASAMAN BARAT'],
        ['0811', 'KABUPATEN DHARMASRAYA'],             ['0810', 'KABUPATEN SIJUNJUNG'],
        ['0809', 'KABUPATEN PASAMAN'],                 ['0808', 'KABUPATEN LIMA PULUH KOTO'],
        ['0807', 'KABUPATEN AGAM'],                    ['0806', 'KABUPATEN PADANG PARIAMAN'],
        ['0805', 'KABUPATEN TANAH DATAR'],             ['0804', 'KABUPATEN SOLOK SELATAN'],
        ['0803', 'KABUPATEN SOLOK'],                   ['0802', 'KABUPATEN PESISIR SELATAN'],
        ['0801', 'KABUPATEN KEPULAUAN MENTAWAI'],      ['0758', 'GUNUNGSITOLI'],
        ['0757', 'PADANGSIDIMPUAN'],                   ['0756', 'BINJAI'],
        ['0755', 'MEDAN'],                             ['0754', 'TEBING TINGGI'],
        ['0753', 'PEMATANG SIANTAR'],                  ['0752', 'TANJUNG BALAI'],
        ['0751', 'SIBOLGA'],                           ['0725', 'KABUPATEN BATU BARA'],
        ['0724', 'KABUPATEN PADANG LAWAS'],            ['0723', 'KABUPATEN PADANG LAWAS UTARA'],
        ['0722', 'KABUPATEN SAMOSIR'],                 ['0721', 'KABUPATEN NIAS BARAT'],
        ['0720', 'KABUPATEN NIAS UTARA'],              ['0719', 'KABUPATEN LABUHAN BATU UTARA'],
        ['0718', 'KABUPATEN LABUHAN BATU SELATAN'],    ['0717', 'KABUPATEN SERDANG BEDAGAI'],
        ['0716', 'KABUPATEN PAKPAK BHARAT'],           ['0715', 'KABUPATEN HUMBANG HASUNDUTAN'],
        ['0714', 'KABUPATEN NIAS SELATAN'],            ['0713', 'KABUPATEN LANGKAT'],
        ['0712', 'KABUPATEN DELI SERDANG'],            ['0711', 'KABUPATEN KARO'],
        ['0710', 'KABUPATEN DAIRI'],                   ['0709', 'KABUPATEN SIMALUNGUN'],
        ['0708', 'KABUPATEN ASAHAN'],                  ['0707', 'KABUPATEN LABUHAN BATU'],
        ['0706', 'KABUPATEN TOBA SAMOSIR'],            ['0705', 'KABUPATEN TAPANULI UTARA'],
        ['0704', 'KABUPATEN TAPANULI TENGAH'],         ['0703', 'KABUPATEN TAPANULI SELATAN'],
        ['0702', 'KABUPATEN MANDAILING NATAL'],        ['0701', 'KABUPATEN NIAS'],
        ['0655', 'SUBUSLUSSALAM'],                     ['0654', 'LHOKSEUMAWE'],
        ['0653', 'LANGSA'],                            ['0652', 'SABANG'],
        ['0651', 'BANDA ACEH'],                        ['0618', 'PIDIE JAYA'],
        ['0617', 'KABUPATEN BENER MERIAH'],            ['0616', 'KABUPATEN ACEH JAYA'],
        ['0615', 'KABUPATEN NAGAN RAYA'],              ['0614', 'KABUPATEN ACEH TAMIANG'],
        ['0613', 'KABUPATEN GAYO LUWES'],              ['0612', 'KABUPATEN ACEH BARAT DAYA'],
        ['0611', 'KABUPATEN ACEH UTARA'],              ['0610', 'KABUPATEN BIREUEN'],
        ['0609', 'KABUPATEN PIDIE'],                   ['0608', 'KABUPATEN ACEH BESAR'],
        ['0607', 'KABUPATEN ACEH BARAT'],              ['0606', 'KABUPATEN ACEH TENGAH'],
        ['0605', 'KABUPATEN ACEH TIMUR'],              ['0604', 'KABUPATEN ACEH TENGGARA'],
        ['0603', 'KABUPATEN ACEH SELATAN'],            ['0602', 'KABUPATEN ACEH SINGKIL'],
        ['0601', 'KABUPATEN SIMEULUE'],                ['0559', 'BATU'],
        ['0558', 'SURABAYA'],                          ['0557', 'MADIUN'],
        ['0556', 'MOJOKERTO'],                         ['0555', 'PASURUAN'],
        ['0554', 'PROBOLINGGO'],                       ['0553', 'MALANG'],
        ['0552', 'BLITAR'],                            ['0551', 'KEDIRI'],
        ['0529', 'KABUPATEN SUMENEP'],                 ['0528', 'KABUPATEN PAMEKASAN'],
        ['0527', 'KABUPATEN SAMPANG'],                 ['0526', 'KABUPATEN BANGKALAN'],
        ['0525', 'KABUPATEN GRESIK'],                  ['0524', 'KABUPATEN LAMONGAN'],
        ['0523', 'KABUPATEN TUBAN'],                   ['0522', 'KABUPATEN BOJONEGORO'],
        ['0521', 'KABUPATEN NGAWI'],                   ['0520', 'KABUPATEN MAGETAN'],
        ['0519', 'KABUPATEN MADIUN'],                  ['0518', 'KABUPATEN NGANJUK'],
        ['0517', 'KABUPATEN JOMBANG'],                 ['0516', 'KABUPATEN MOJOKERTO'],
        ['0515', 'KABUPATEN SIDOARJO'],                ['0514', 'KABUPATEN PASURUAN'],
        ['0513', 'KABUPATEN PROBOLINGGO'],             ['0512', 'KABUPATEN SITUBONDO'],
        ['0511', 'KABUPATEN BONDOWOSO'],               ['0510', 'KABUPATEN BANYUWANGI'],
        ['0509', 'KABUPATEN JEMBER'],                  ['0508', 'KABUPATEN LUMAJANG'],
        ['0507', 'KABUPATEN MALANG'],                  ['0506', 'KABUPATEN KEDIRI'],
        ['0505', 'KABUPATEN BLITAR'],                  ['0504', 'KABUPATEN TULUNGAGUNG'],
        ['0503', 'KABUPATEN TRENGGALEK'],              ['0502', 'KABUPATEN PONOROGO'],
        ['0501', 'KABUPATEN PACITAN'],                 ['0451', 'YOGYAKARTA'],
        ['0404', 'KABUPATEN SLEMAN'],                  ['0403', 'KABUPATEN GUNUNG KIDUL'],
        ['0402', 'KABUPATEN BANTUL'],                  ['0401', 'KABUPATEN KULON PROGO'],
        ['0356', 'TEGAL'],                             ['0355', 'PEKALONGAN'],
        ['0354', 'SEMARANG'],                          ['0353', 'SALATIGA'],
        ['0352', 'SURAKARTA'],                         ['0351', 'MAGELANG'],
        ['0329', 'KABUPATEN BREBES'],                  ['0328', 'KABUPATEN TEGAL'],
        ['0327', 'KABUPATEN PEMALANG'],                ['0326', 'KABUPATEN PEKALONGAN'],
        ['0325', 'KABUPATEN BATANG'],                  ['0324', 'KABUPATEN KENDAL'],
        ['0323', 'KABUPATEN TEMANGGUNG'],              ['0322', 'KABUPATEN SEMARANG'],
        ['0321', 'KABUPATEN DEMAK'],                   ['0320', 'KABUPATEN JEPARA'],
        ['0319', 'KABUPATEN KUDUS'],                   ['0318', 'KABUPATEN PATI'],
        ['0317', 'KABUPATEN REMBANG'],                 ['0316', 'KABUPATEN BLORA'],
        ['0315', 'KABUPATEN GROBOGAN'],                ['0314', 'KABUPATEN SRAGEN'],
        ['0313', 'KABUPATEN KARANG ANYAR'],            ['0312', 'KABUPATEN WONOGIRI'],
        ['0311', 'KABUPATEN SUKOHARJO'],               ['0310', 'KABUPATEN KLATEN'],
        ['0309', 'KABUPATEN BOYOLALI'],                ['0308', 'KABUPATEN MAGELANG'],
        ['0307', 'KABUPATEN WONOSOBO'],                ['0306', 'KABUPATEN PURWOREJO'],
        ['0305', 'KABUPATEN KEBUMEN'],                 ['0304', 'KABUPATEN BANJARNEGARA'],
        ['0303', 'KABUPATEN PURBALINGGA'],             ['0302', 'KABUPATEN BANYUMAS'],
        ['0301', 'KABUPATEN CILACAP'],                 ['0259', 'BANJAR'],
        ['0258', 'TASIK MALAYA'],                      ['0257', 'CIMAHI'],
        ['0256', 'DEPOK'],                             ['0255', 'BEKASI'],
        ['0254', 'CIREBON'],                           ['0253', 'BANDUNG'],
        ['0252', 'SUKABUMI'],                          ['0251', 'BOGOR'],
        ['0216', 'KABUPATEN BEKASI'],                  ['0215', 'KABUPATEN KARAWANG'],
        ['0214', 'KABUPATEN PURWAKARTA'],              ['0213', 'KABUPATEN SUBANG'],
        ['0212', 'KABUPATEN INDRAMAYU'],               ['0211', 'KABUPATEN SUMEDANG'],
        ['0210', 'KABUPATEN MAJALENGKA'],              ['0209', 'KABUPATEN CIREBON'],
        ['0208', 'KABUPATEN KUNINGAN'],                ['0207', 'KABUPATEN CIAMIS'],
        ['0206', 'KABUPATEN TASIK MALAYA'],            ['0205', 'KABUPATEN GARUT'],
        ['0204', 'KABUPATEN BANDUNG'],                 ['0203', 'KABUPATEN CIANJUR'],
        ['0202', 'KABUPATEN SUKABUMI'],                ['0201', 'KABUPATEN BOGOR'],
        ['0155', 'JAKARTA UTARA'],                     ['0154', 'JAKARTA BARAT'],
        ['0153', 'JAKARTA PUSAT'],                     ['0152', 'JAKARTA TIMUR'],
        ['0151', 'JAKARTA SELATAN'],                   ['0101', 'KABUPATEN KEPULAUAN SERIBU'],
        ['1007', 'KABUPATEN TANJUNG JABUNG BARAT'],    ['1008', 'KABUPATEN TEBO'],
        ['1009', 'KABUPATEN BUNGO'],                   ['1010', 'KABUPATEN SUNGAI PENUH'],
        ['1051', 'JAMBI'],
        ['1101', 'KABUPATEN OGAN KOMERING ULU'],       ['1102', 'KABUPATEN OGAN KOMERING ILIR'],
        ['1103', 'KABUPATEN MUARA ENIM'],              ['1104', 'KABUPATEN LAHAT'],
        ['1105', 'KABUPATEN MUSI RAWAS'],              ['1106', 'KABUPATEN MUSI BANYUASIN'],
        ['1107', 'KABUPATEN BANYUASIN'],               ['1108', 'KABUPATEN OGAN ILIR'],
        ['1109', 'KABUPATEN OKU TIMUR'],               ['1110', 'KABUPATEN OKU SELATAN'],
        ['1111', 'KABUPATEN EMPAT LAWANG'],            ['1151', 'PALEMBANG'],
        ['1152', 'PRABUMULIH'],                         ['1153', 'PAGAR ALAM'],
        ['1154', 'LUBUK LINGGAU'],
        ['1201', 'KABUPATEN LAMPUNG BARAT'],            ['1202', 'KABUPATEN TANGGAMUS'],
        ['1203', 'KABUPATEN LAMPUNG SELATAN'],          ['1204', 'KABUPATEN LAMPUNG TIMUR'],
        ['1205', 'KABUPATEN LAMPUNG TENGAH'],           ['1206', 'KABUPATEN LAMPUNG UTARA'],
        ['1207', 'KABUPATEN WAY KANAN'],                ['1208', 'KABUPATEN TULANG BAWANG'],
        ['1209', 'KABUPATEN PESAWARAN'],                ['1251', 'BANDAR LAMPUNG'],
        ['1252', 'METRO'],
        ['1301', 'KABUPATEN SAMBAS'],                   ['1302', 'KABUPATEN BENGKAYANG'],
        ['1303', 'KABUPATEN LANDAK'],                   ['1304', 'KABUPATEN PONTIANAK'],
        ['1305', 'KABUPATEN SANGGAU'],                  ['1306', 'KABUPATEN KETAPANG'],
        ['1307', 'KABUPATEN SINTANG'],                  ['1308', 'KABUPATEN KAPUAS HULU'],
        ['1309', 'KABUPATEN SEKADAU'],                  ['1310', 'KABUPATEN MELAWI'],
        ['1311', 'KABUPATEN KAYONG UTARA'],             ['1312', 'KABUPATEN KUBU RAYA'],
        ['1351', 'PONTIANAK'],                          ['1352', 'SINGKAWANG'],
        ['1401', 'KABUPATEN KOTAWARINGIN BARAT'],       ['1402', 'KABUPATEN KOTAWARINGIN TIMUR'],
        ['1403', 'KABUPATEN KAPUAS'],                   ['1404', 'KABUPATEN BARITO SELATAN'],
        ['1405', 'KABUPATEN BARITO UTARA'],             ['1406', 'KABUPATEN SUKAMARA'],
        ['1407', 'KABUPATEN LAMANDAU'],                 ['1408', 'KABUPATEN SERUYAN'],
        ['1409', 'KABUPATEN KATINGAN'],                 ['1410', 'KABUPATEN PULANG PISAU'],
        ['1411', 'KABUPATEN GUNUNG MAS'],               ['1412', 'KABUPATEN BARITO TIMUR'],
        ['1413', 'KABUPATEN MURUNG RAYA'],              ['1451', 'PALANGKA RAYA'],
        ['1501', 'KABUPATEN TANAH LAUT'],               ['1502', 'KABUPATEN KOTABARU'],
        ['1503', 'KABUPATEN BANJAR'],                   ['1504', 'KABUPATEN BARITO KUALA'],
        ['1505', 'KABUPATEN TAPIN'],                    ['1506', 'KABUPATEN HULU SUNGAI SELATAN'],
        ['1507', 'KABUPATEN HULU SUNGAI TENGAH'],       ['1508', 'KABUPATEN HULU SUNGAI UTARA'],
        ['1509', 'KABUPATEN TABALONG'],                 ['1510', 'KABUPATEN TANAH BUMBU'],
        ['1511', 'KABUPATEN BALANGAN'],                 ['1551', 'BANJARMASIN'],
        ['1552', 'BANJARBARU'],
        ['1601', 'KABUPATEN PASER'],                    ['1602', 'KABUPATEN KUTAI BARAT'],
        ['1603', 'KABUPATEN KUTAI KARTANEGARA'],        ['1604', 'KABUPATEN KUTAI TIMUR'],
        ['1605', 'KABUPATEN BERAU'],                    ['1606', 'KABUPATEN MALINAU'],
        ['1607', 'KABUPATEN BULUNGAN'],                 ['1608', 'KABUPATEN NUNUKAN'],
        ['1609', 'KABUPATEN PENAJAM PASER UTARA'],      ['1610', 'KABUPATEN TANA TIDUNG'],
        ['1651', 'BALIKPAPAN'],                         ['1652', 'SAMARINDA'],
        ['1653', 'TARAKAN'],                            ['1654', 'BONTANG'],
        ['1701', 'KABUPATEN BOLAANG MONGONDOW'],        ['1702', 'KABUPATEN MINAHASA'],
        ['1703', 'KABUPATEN KEPULAUAN SANGIHE'],        ['1704', 'KABUPATEN KEPULAUAN TALAUD'],
        ['1705', 'KABUPATEN MINAHASA SELATAN'],         ['1706', 'KABUPATEN MINAHASA UTARA'],
        ['1707', 'KAB BOLAANG MONGONDOW TIMUR'],        ['1708', 'KAB BOLAANG MONGONDOW SELATAN'],
        ['1709', 'KABUPATEN MINAHASA TENGGARA'],        ['1710', 'KAB BOLAANG MONGONDOW UTARA'],
        ['1711', 'KAB SIAU TAGULANDANG BIARO'],         ['1751', 'MANADO'],
        ['1752', 'BITUNG'],                             ['1753', 'TOMOHON'],
        ['1754', 'KOTAMOBAGU'],
        ['1801', 'KABUPATEN BANGGAI KEPULAUAN'],        ['1802', 'KABUPATEN BANGGAI'],
        ['1803', 'KABUPATEN MOROWALI'],                 ['1804', 'KABUPATEN POSO'],
        ['1805', 'KABUPATEN DONGGALA'],                 ['1806', 'KABUPATEN TOLI-TOLI'],
        ['1807', 'KABUPATEN BUOL'],                     ['1808', 'KABUPATEN PARIGI MOUTONG'],
        ['1809', 'KABUPATEN TOJO UNA-UNA'],             ['1810', 'KABUPATEN SIGI'],
        ['1851', 'PALU'],
        ['1901', 'KABUPATEN SELAYAR'],                  ['1902', 'KABUPATEN BULUKUMBA'],
        ['1903', 'KABUPATEN BANTAENG'],                 ['1904', 'KABUPATEN JENEPONTO'],
        ['1905', 'KABUPATEN TAKALAR'],                  ['1906', 'KABUPATEN GOWA'],
        ['1907', 'KABUPATEN SINJAI'],                   ['1908', 'KABUPATEN MAROS'],
        ['1909', 'KABUPATEN PANGKAJENE'],               ['1910', 'KABUPATEN BARRU'],
        ['1911', 'KABUPATEN BONE'],                     ['1912', 'KABUPATEN SOPPENG'],
        ['1913', 'KABUPATEN WAJO'],                     ['1914', 'KABUPATEN SIDENRENG RAPPANG'],
        ['1915', 'KABUPATEN PINRANG'],                  ['1916', 'KABUPATEN ENREKANG'],
        ['1917', 'KABUPATEN LUWU'],                     ['1918', 'KABUPATEN TANA TORAJA'],
        ['1922', 'KABUPATEN LUWU UTARA'],               ['1925', 'KABUPATEN LUWU TIMUR'],
        ['1926', 'KABUPATEN TORAJA UTARA'],             ['1951', 'MAKASSAR'],
        ['1952', 'PARE-PARE'],                          ['1953', 'PALOPO'],
        ['2001', 'KABUPATEN BUTON'],                    ['2002', 'KABUPATEN MUNA'],
        ['2003', 'KABUPATEN KONAWE'],                   ['2004', 'KABUPATEN KOLAKA'],
        ['2005', 'KABUPATEN WAKATOBI'],                 ['2006', 'KABUPATEN BOMBANA'],
        ['2007', 'KABUPATEN KOLAKA UTARA'],             ['2008', 'KABUPATEN KONAWE SELATAN'],
        ['2009', 'KABUPATEN KONAWE UTARA'],             ['2010', 'KABUPATEN BUTON UTARA'],
        ['2051', 'KENDARI'],                            ['2052', 'BAU-BAU'],
        ['2101', 'KABUPATEN MALUKU TENGGARA BARA'],     ['2102', 'KABUPATEN MALUKU TENGGARA'],
        ['2103', 'KABUPATEN MALUKU TENGAH'],            ['2104', 'KABUPATEN BURU'],
        ['2105', 'KABUPATEN SERAM BAGIAN BARAT'],       ['2106', 'KABUPATEN SERAM BARAT TIMUR'],
        ['2107', 'KABUPATEN KEPULAUAN ARU'],            ['2108', 'KABUPATEN MALUKU BARAT DAYA'],
        ['2109', 'KABUPATEN BURU SELATAN'],             ['2151', 'AMBON'],
        ['2152', 'TUAL'],
        ['2201', 'KABUPATEN JEMBRANA'],                 ['2202', 'KABUPATEN TABANAN'],
        ['2203', 'KABUPATEN BADUNG'],                   ['2204', 'KABUPATEN GIANYAR'],
        ['2205', 'KABUPATEN KLUNGKUNG'],                ['2206', 'KABUPATEN BANGLI'],
        ['2207', 'KABUPATEN KARANGASEM'],               ['2208', 'KABUPATEN BULELENG'],
        ['2251', 'DENPASAR'],
        ['2301', 'KABUPATEN LOMBOK BARAT'],             ['2302', 'KABUPATEN LOMBOK TENGAH'],
        ['2303', 'KABUPATEN LOMBOK TIMUR'],             ['2304', 'KABUPATEN SUMBAWA'],
        ['2305', 'KABUPATEN DOMPU'],                    ['2306', 'KABUPATEN BIMA'],
        ['2307', 'KABUPATEN SUMBAWA BARAT'],            ['2308', 'KABUPATEN LOMBOK UTARA'],
        ['2351', 'MATARAM'],                            ['2352', 'BIMA'],
        ['2401', 'KABUPATEN SUMBA BARAT'],              ['2402', 'KABUPATEN SUMBA TIMUR'],
        ['2403', 'KABUPATEN KUPANG'],                   ['2404', 'KABUPATEN TIMOR TENGAH SELATAN'],
        ['2405', 'KABUPATEN TIMOR TENGAH UTARA'],       ['2406', 'KABUPATEN BELU'],
        ['2407', 'KABUPATEN ALOR'],                     ['2408', 'KABUPATEN LEMBATA'],
        ['2409', 'KABUPATEN FLORES TIMUR'],             ['2410', 'KABUPATEN SIKKA'],
        ['2411', 'KABUPATEN ENDE'],                     ['2412', 'KABUPATEN NGADA'],
        ['2413', 'KABUPATEN MANGGARAI'],                ['2414', 'KABUPATEN ROTE NDAO'],
        ['2415', 'KABUPATEN MANGGARAI BARAT'],          ['2416', 'KABUPATEN SUMBA TENGAH'],
        ['2417', 'KABUPATEN SUMBA BARAT DAYA'],         ['2418', 'KABUPATEN SABU RAIJUA'],
        ['2419', 'KABUPATEN NAGEKEO'],                  ['2420', 'KABUPATEN MANGGARAI TIMUR'],
        ['2451', 'KUPANG'],
        ['2501', 'KABUPATEN MERAUKE'],                  ['2502', 'KABUPATEN JAYA WIJAYA'],
        ['2503', 'KABUPATEN JAYAPURA'],                 ['2504', 'KABUPATEN NABIRE'],
        ['2505', 'KABUPATEN YAPEN WAROPEN'],            ['2506', 'KABUPATEN BIAK NUMFOR'],
        ['2507', 'KABUPATEN PANIAI'],                   ['2508', 'KABUPATEN PUNCAK JAYA'],
        ['2509', 'KABUPATEN MIMIKA'],                   ['2510', 'KABUPATEN BOVEN DIGOEL'],
        ['2511', 'KABUPATEN MAPPI'],                    ['2512', 'KABUPATEN ASMAT'],
        ['2513', 'KABUPATEN YAKUHIMO'],                 ['2514', 'KABUPATEN PEGUNUNGAN BINTANG'],
        ['2515', 'KABUPATEN TOLIKARA'],                 ['2516', 'KABUPATEN SARMI'],
        ['2517', 'KABUPATEN KEEROM'],                   ['2518', 'KABUPATEN WAROPEN'],
        ['2519', 'KABUPATEN SUPIORI'],                  ['2520', 'KABUPATEN NDUGA'],
        ['2521', 'KABUPATEN LANNY JAYA'],               ['2522', 'KABUPATEN MAMBERAMO TENGAH'],
        ['2523', 'KABUPATEN YALIMO'],                   ['2524', 'KABUPATEN MAMBERAMO RAYA'],
        ['2525', 'KABUPATEN PUNCAK'],                   ['2526', 'KABUPATEN INTAN JAYA'],
        ['2527', 'KABUPATEN DEIYAI'],                   ['2528', 'KABUPATEN DOGIYAI'],
        ['2551', 'JAYAPURA'],
        ['2601', 'KABUPATEN BENGKULU SELATAN'],         ['2602', 'KABUPATEN REJANG LEBONG'],
        ['2603', 'KABUPATEN BENGKULU UTARA'],           ['2604', 'KABUPATEN KAUR'],
        ['2605', 'KABUPATEN SELUMA'],                   ['2606', 'KABUPATEN MUKO-MUKO'],
        ['2607', 'KABUPATEN LEBONG'],                   ['2608', 'KABUPATEN KEPAHIANG'],
        ['2609', 'KABUPATEN BENGKULU TENGAH'],          ['2651', 'BENGKULU'],
        ['2801', 'KABUPATEN PANDEGLANG'],               ['2802', 'KABUPATEN LEBAK'],
        ['2803', 'KABUPATEN TANGERANG'],                ['2804', 'KABUPATEN SERANG'],
        ['2851', 'TANGERANG'],                          ['2852', 'CILEGON'],
        ['2901', 'KABUPATEN HALMAHERA BARAT'],          ['2902', 'KABUPATEN HALMAHERA TENGAH'],
        ['2903', 'KABUPATEN KEPULAUAN SULA'],           ['2904', 'KABUPATEN HALMAHERA SELATAN'],
        ['2905', 'KABUPATEN HALMAHERA UTARA'],          ['2906', 'KABUPATEN HALMAHERA TIMUR'],
        ['2907', 'KABUPATEN PULAU MOROTAI'],            ['2951', 'TERNATE'],
        ['2952', 'TIDORE KEPULAUAN'],
        ['3001', 'KABUPATEN BANGKA'],                   ['3002', 'KABUPATEN BELITUNG'],
        ['3003', 'KABUPATEN BANGKA SELATAN'],           ['3004', 'KABUPATEN BANGKA TENGAH'],
        ['3005', 'KABUPATEN BANGKA BARAT'],             ['3006', 'KABUPATEN BELITUNG TIMUR'],
        ['3051', 'PANGKALPINANG'],
        ['3101', 'KABUPATEN BOALEMO'],                  ['3102', 'KABUPATEN GORONTALO'],
        ['3103', 'KABUPATEN POHUWATO'],                 ['3104', 'KABUPATEN BONE BOLANGO'],
        ['3151', 'GORONTALO'],
        ['3201', 'KABUPATEN FAK-FAK'],                  ['3202', 'KABUPATEN SORONG'],
        ['3203', 'KABUPATEN MANOKWARI'],                ['3204', 'KABUPATEN KAIMANA'],
        ['3205', 'KABUPATEN SORONG SELATAN'],           ['3206', 'KABUPATEN RAJA AMPAT'],
        ['3207', 'KABUPATEN TELUK BINTUNI'],            ['3208', 'KABUPATEN TELUK WONDAMA'],
        ['3251', 'SORONG'],
        ['3301', 'KABUPATEN KARIMUN'],                  ['3302', 'KABUPATEN KEPULAUAN ANAMBAS'],
        ['3303', 'KABUPATEN NATUNA'],                   ['3304', 'KABUPATEN BINTAN'],
        ['3305', 'KABUPATEN LINGGA'],                   ['3351', 'BATAM'],
        ['3352', 'TANJUNG PINANG'],
        ['3401', 'KABUPATEN MAMUJU'],                   ['3402', 'KABUPATEN MAMUJU UTARA'],
        ['3403', 'KABUPATEN MAJENE'],                   ['3404', 'KABUPATEN POLEWALI MANDAR'],
        ['3405', 'KABUPATEN MAMASA'],
    ];

    public function up(): void
    {
        foreach ($this->kabupatenData as $row) {
            DB::table('kabupatens')
                ->where('kode', $row[0])
                ->update(['nama' => $row[1]]);
        }
    }

    public function down(): void
    {
        // No rollback needed — original data was wrong anyway
    }
};
